### ISSUE TITLE
addons path list view but not install sign

### ISSUE THREAD

**Issue by johnfelipe** [hsd/sign#5]
addons_path = /opt/openerp/server/openerp/addons/aeroo,/opt/openerp/server/openerp/addons/listview-images

but not install sign.

Help fix it

**Comment by mrvdb** [comment]
- addons_path should contain '/opt/openerp/server/openerp/addons/'

**Comment by johnfelipe** [comment]
All right, still dont work yur app

**Comment by mrvdb** [comment]
sorry to hear that, i don't know what goes wrong in your situation. I cannot reproduce any of the problems you have.

**Comment by johnfelipe** [comment]
i have Versión 7.0-20140225-002826 in ubuntu, i install with wget night vers.

**Comment by mrvdb** [comment]
With that specific nightly I can reproduce the problem.

**Comment by johnfelipe** [comment]
7.0-20140225-002826

**Comment by mrvdb** [comment]
The problem is that it does not work when the name of the module contains a '-' (minus) character. If you rename the listview-images folder to listview_images it should work. The 'sign' module already contains the proper dependency, so I ran into this issue earlier.

**Comment by mrvdb** [comment]
See https://github.com/hsd/listview_images/issues/1 (repository renamed)

**Comment by johnfelipe** [comment]
It work, tnks, but show me this:

```
   Uncaught Error: QWeb2 - template['ViewManagerDebug']: Runtime Error: TypeError: Cannot read property 'view_id' of undefined
```

**Comment by mrvdb** [comment]
There should be more info in the server log. Please, if you encounter errors, provide as much info as possible, otherwise I need to guess what is happening.
